<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="1" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-04-26T19:03:33 IST" name="Default suite" finished-at="2025-04-26T19:03:58 IST" duration-ms="24698">
    <groups>
    </groups>
    <test started-at="2025-04-26T19:03:33 IST" name="Default test" finished-at="2025-04-26T19:03:58 IST" duration-ms="24698">
      <class name="HumanResourceManagement.LoginandLogoutWithFourCredentials">
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:HumanResourceManagement.LoginandLogoutWithFourCredentials@6ae5aa72]" started-at="2025-04-26T19:03:33 IST" name="beforeTest" finished-at="2025-04-26T19:03:40 IST" duration-ms="6727" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method signature="loginToOHROM(java.lang.String,java.lang.String)[pri:0, instance:HumanResourceManagement.LoginandLogoutWithFourCredentials@6ae5aa72]" started-at="2025-04-26T19:03:40 IST" name="loginToOHROM" data-provider="getLoginData" finished-at="2025-04-26T19:03:43 IST" duration-ms="3554" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[admin123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToOHROM -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:HumanResourceManagement.LoginandLogoutWithFourCredentials@6ae5aa72]" started-at="2025-04-26T19:03:43 IST" name="afterMethod" finished-at="2025-04-26T19:03:46 IST" duration-ms="2997" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginToOHROM status=SUCCESS method=LoginandLogoutWithFourCredentials.loginToOHROM(java.lang.String,java.lang.String)[pri:0, instance:HumanResourceManagement.LoginandLogoutWithFourCredentials@6ae5aa72] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="loginToOHROM(java.lang.String,java.lang.String)[pri:0, instance:HumanResourceManagement.LoginandLogoutWithFourCredentials@6ae5aa72]" started-at="2025-04-26T19:03:46 IST" name="loginToOHROM" data-provider="getLoginData" finished-at="2025-04-26T19:03:50 IST" duration-ms="3111" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[anu]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[anusha123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at HumanResourceManagement.LoginandLogoutWithFourCredentials.loginToOHROM(LoginandLogoutWithFourCredentials.java:72)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToOHROM -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:HumanResourceManagement.LoginandLogoutWithFourCredentials@6ae5aa72]" started-at="2025-04-26T19:03:50 IST" name="afterMethod" finished-at="2025-04-26T19:03:50 IST" duration-ms="18" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginToOHROM status=FAILURE method=LoginandLogoutWithFourCredentials.loginToOHROM(java.lang.String,java.lang.String)[pri:0, instance:HumanResourceManagement.LoginandLogoutWithFourCredentials@6ae5aa72] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="loginToOHROM(java.lang.String,java.lang.String)[pri:0, instance:HumanResourceManagement.LoginandLogoutWithFourCredentials@6ae5aa72]" started-at="2025-04-26T19:03:50 IST" name="loginToOHROM" data-provider="getLoginData" finished-at="2025-04-26T19:03:52 IST" duration-ms="2282" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[sharmi]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[sharmi123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at HumanResourceManagement.LoginandLogoutWithFourCredentials.loginToOHROM(LoginandLogoutWithFourCredentials.java:72)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToOHROM -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:HumanResourceManagement.LoginandLogoutWithFourCredentials@6ae5aa72]" started-at="2025-04-26T19:03:52 IST" name="afterMethod" finished-at="2025-04-26T19:03:53 IST" duration-ms="798" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginToOHROM status=FAILURE method=LoginandLogoutWithFourCredentials.loginToOHROM(java.lang.String,java.lang.String)[pri:0, instance:HumanResourceManagement.LoginandLogoutWithFourCredentials@6ae5aa72] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="loginToOHROM(java.lang.String,java.lang.String)[pri:0, instance:HumanResourceManagement.LoginandLogoutWithFourCredentials@6ae5aa72]" started-at="2025-04-26T19:03:53 IST" name="loginToOHROM" data-provider="getLoginData" finished-at="2025-04-26T19:03:55 IST" duration-ms="2284" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[add]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[admin123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at HumanResourceManagement.LoginandLogoutWithFourCredentials.loginToOHROM(LoginandLogoutWithFourCredentials.java:72)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToOHROM -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:HumanResourceManagement.LoginandLogoutWithFourCredentials@6ae5aa72]" started-at="2025-04-26T19:03:55 IST" name="afterMethod" finished-at="2025-04-26T19:03:55 IST" duration-ms="5" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginToOHROM status=FAILURE method=LoginandLogoutWithFourCredentials.loginToOHROM(java.lang.String,java.lang.String)[pri:0, instance:HumanResourceManagement.LoginandLogoutWithFourCredentials@6ae5aa72] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="loginToOHROM(java.lang.String,java.lang.String)[pri:0, instance:HumanResourceManagement.LoginandLogoutWithFourCredentials@6ae5aa72]" started-at="2025-04-26T19:03:55 IST" name="loginToOHROM" data-provider="getLoginData" finished-at="2025-04-26T19:03:57 IST" duration-ms="2280" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[priya]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[priya123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at HumanResourceManagement.LoginandLogoutWithFourCredentials.loginToOHROM(LoginandLogoutWithFourCredentials.java:72)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToOHROM -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:HumanResourceManagement.LoginandLogoutWithFourCredentials@6ae5aa72]" started-at="2025-04-26T19:03:57 IST" name="afterMethod" finished-at="2025-04-26T19:03:57 IST" duration-ms="7" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginToOHROM status=FAILURE method=LoginandLogoutWithFourCredentials.loginToOHROM(java.lang.String,java.lang.String)[pri:0, instance:HumanResourceManagement.LoginandLogoutWithFourCredentials@6ae5aa72] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:HumanResourceManagement.LoginandLogoutWithFourCredentials@6ae5aa72]" started-at="2025-04-26T19:03:57 IST" name="afterTest" finished-at="2025-04-26T19:03:58 IST" duration-ms="602" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- HumanResourceManagement.LoginandLogoutWithFourCredentials -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
